export type Segment = { text: string; highlight?: boolean };

export const pt = {
    Tittle: 'Meus conhecimentos!',
    Category: 'Escolha um tipo',

    BackendDesc: [
      { text: 'Projeto e mantenho APIs robustas e escaláveis utilizando ' },
      { text: 'Kotlin, Java e Spring', highlight: true },
      { text: ', com integração a sistemas de mensageria como ' },
      { text: 'Kafka e RabbitMQ', highlight: true },
      { text: '. Tenho experiência com ' },
      { text: 'AWS', highlight: true },
      { text: ', bancos de dados relacionais, estratégias de caching e pipelines de ' },
      { text: 'CI/CD', highlight: true },
      { text: ', sempre com foco em ' },
      { text: 'design de sistemas', highlight: true },
      { text: ', ' },
      { text: 'observabilidade', highlight: true },
      { text: ' e ' },
      { text: 'otimização de performance', highlight: true },
      { text: '.' },
    ] as Segment[],

    MobileDesc: [
      { text: 'Desenvolvo aplicativos móveis híbridos e nativos utilizando ' },
      { text: 'Flutter, React Native, Java e Kotlin', highlight: true },
      { text: ', com experiência sólida no ecossistema ' },
      { text: 'Android', highlight: true },
      { text: '. Possuo também conhecimentos em ' },
      { text: 'Swift', highlight: true },
      { text: ' para desenvolvimento ' },
      { text: 'iOS', highlight: true },
      { text: ', priorizando arquitetura limpa e experiências de usuário confiáveis.' },
    ] as Segment[],

    securityDesc: [
      { text: 'Realizo testes de penetração e identificação de vulnerabilidades em aplicativos móveis, utilizando ferramentas como ' },
      { text: 'Jadx', highlight: true },
      { text: ' para descompilação de APKs, ' },
      { text: 'Frida', highlight: true },
      { text: ' para bypass de segurança e manipulação de runtime, e ' },
      { text: 'Burp Suite', highlight: true },
      { text: ' para análise de tráfego e mapeamento de rotas vulneráveis. Aplico técnicas de ' },
      { text: 'análise estática e dinâmica', highlight: true },
      { text: ', incluindo exploração de falhas em comunicação insegura, ' },
      { text: 'bypass de autenticação', highlight: true },
      { text: ' e ' },
      { text: 'fuzzing', highlight: true },
      { text: ' de parâmetros de entrada.' },
    ] as Segment[],
  }

  export const en = {
    Tittle: 'My knowledges!',
    Category: 'Choose a type!',

    BackendDesc: [
      { text: 'I design and maintain robust and scalable APIs using ' },
      { text: 'Kotlin, Java and Spring', highlight: true },
      { text: ', with integration to messaging systems like ' },
      { text: 'Kafka and RabbitMQ', highlight: true },
      { text: '. I have experience with ' },
      { text: 'AWS', highlight: true },
      { text: ', relational databases, caching strategies and ' },
      { text: 'CI/CD', highlight: true },
      { text: ' pipelines, always focusing on ' },
      { text: 'system design', highlight: true },
      { text: ', ' },
      { text: 'observability', highlight: true },
      { text: ' and ' },
      { text: 'performance optimization', highlight: true },
      { text: '.' },
    ] as Segment[],

    MobileDesc: [
      { text: 'I develop hybrid and native mobile applications using ' },
      { text: 'Flutter, React Native, Java and Kotlin', highlight: true },
      { text: ', with solid experience in the ' },
      { text: 'Android', highlight: true },
      { text: ' ecosystem. I also have knowledge in ' },
      { text: 'Swift', highlight: true },
      { text: ' for ' },
      { text: 'iOS', highlight: true },
      { text: ' development, prioritizing clean architecture and reliable user experiences.' },
    ] as Segment[],

    securityDesc: [
      { text: 'I perform penetration testing and vulnerability identification in mobile applications, using tools like ' },
      { text: 'Jadx', highlight: true },
      { text: ' for APK decompilation, ' },
      { text: 'Frida', highlight: true },
      { text: ' for security bypass and runtime manipulation, and ' },
      { text: 'Burp Suite', highlight: true },
      { text: ' for traffic analysis and mapping of vulnerable routes. I apply ' },
      { text: 'static and dynamic analysis', highlight: true },
      { text: ' techniques, including exploitation of insecure communication flaws, ' },
      { text: 'authentication bypass', highlight: true },
      { text: ' and input parameter ' },
      { text: 'fuzzing', highlight: true },
      { text: '.' },
    ] as Segment[],
  }
